# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[22, 94],
       [ 3,  7],
       [33, 95],
       [32, 29],
       [52, 97],
       [17,  9],
       [61, 20],
       [70, 41],
       [64, 38],
       [40, 50]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

C:\Users\06\Anaconda3\envs\srodowisko\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.28358209, 0.96666667],
       [0.        , 0.        ],
       [0.44776119, 0.97777778],
       [0.43283582, 0.24444444],
       [0.73134328, 1.        ],
       [0.20895522, 0.02222222],
       [0.86567164, 0.14444444],
       [1.        , 0.37777778],
       [0.91044776, 0.34444444],
       [0.55223881, 0.47777778]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

C:\Users\06\Anaconda3\envs\srodowisko\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[0.28358209, 0.96666667],
       [0.        , 0.        ],
       [0.44776119, 0.97777778],
       [0.43283582, 0.24444444],
       [0.73134328, 1.        ],
       [0.20895522, 0.02222222],
       [0.86567164, 0.14444444],
       [1.        , 0.37777778],
       [0.91044776, 0.34444444],
       [0.55223881, 0.47777778]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0   98  61  39     24
1   99  65  67      5
2   24  48  77     34
3  100  10  99     59
4   90  40  50     25

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!